export const BATTLE_BOT_NAMES = [
  "Nguyễn Minh Anh", "Trần Quốc Bảo", "Lê Hoàng Nam", "Phạm Gia Huy", "Hoàng Ngọc Mai",
  "Võ Thành Đạt", "Đặng Minh Khang", "Bùi Khánh Linh", "Đỗ Anh Tuấn", "Hồ Thanh Tùng",
  "Nguyễn Hải Đăng", "Trần Bảo Ngọc", "Lê Minh Quang", "Phạm Thùy Dương", "Hoàng Đức Huy",
  "Võ Nhật Minh", "Đặng Phương Anh", "Bùi Tuấn Kiệt", "Đỗ Khánh Vy", "Hồ Gia Bảo",
  "Nguyễn Thanh Bình", "Trần Minh Đức", "Lê Ngọc Trâm", "Phạm Quốc Huy", "Hoàng Anh Thư",
  "Võ Minh Tâm", "Đặng Hải Yến", "Bùi Hoàng Phúc", "Đỗ Minh Châu", "Hồ Nhật Anh",
  "Nguyễn Gia Hân", "Trần Khánh Duy", "Lê Thanh Huyền", "Phạm Minh Hiếu", "Hoàng Quốc Trung",
  "Võ Bảo Anh", "Đặng Thành Công", "Bùi Ngọc Hà", "Đỗ Hoàng Anh", "Hồ Minh Tuấn",
  "Nguyễn Phúc An", "Trần Thảo Nguyên", "Lê Đức Long", "Phạm Ngọc Lan", "Hoàng Minh Triết",
  "Võ Khánh Ngọc", "Đặng Quốc Anh", "Bùi Minh Hằng", "Đỗ Gia Khánh", "Hồ Phương Thảo",
  "Trần Ngọc Hân", "Nguyễn Hoàng Phúc", "Lê Thị Thu Hà", "Phạm Minh Nhật", "Hoàng Thanh Trúc",
  "Võ Đức Anh", "Đặng Bảo Châu", "Bùi Quốc Hưng", "Đỗ Ngọc Diệp", "Hồ Minh Quân",
  "Nguyễn Thảo Vy", "Trần Đức Minh", "Lê Thanh Nhàn", "Phạm Gia Bảo", "Hoàng Mỹ Linh",
  "Võ Hoàng Long", "Đặng Ngọc Ánh", "Bùi Minh Trí", "Đỗ Thanh Hằng", "Hồ Quốc Khánh",
  "Nguyễn Thiên Ân", "Trần Hoàng Sơn", "Lê Bảo Trân", "Phạm Đức Thịnh", "Hoàng Ngọc Bích",
  "Võ Thanh Phong", "Đặng Khánh Ngân", "Bùi Nhật Hào", "Đỗ Phương Linh", "Hồ Tuấn Anh",
  "Nguyễn Minh Thư", "Trần Quốc Việt", "Lê Hải Anh", "Phạm Hoàng Lâm", "Hoàng Thùy Trang",
  "Võ Minh Khôi", "Đặng Gia Linh", "Bùi Thanh Sơn", "Đỗ Nhật Linh", "Hồ Đức Phúc",
  "Nguyễn Ngọc Quỳnh", "Trần Minh Thành", "Lê Gia Nghi", "Phạm Quốc Thiên", "Hoàng Bảo Yến",
  "Võ Anh Khoa", "Đặng Thanh Mai", "Bùi Đức Duy", "Đỗ Thiên Kim", "Hồ Nhật Quang",
] as const;
